name = "jackofalldogs"
main = "worker/index.js"
compatibility_date = "2025-08-07"

[build]
command = "npm run build"

[site]
bucket = "./dist"

[[routes]]
pattern = "jackofalldogs.co.uk/*"
custom_domain = true

[[routes]]
pattern = "www.jackofalldogs.co.uk/*"
custom_domain = true

[[routes]]
pattern = "jackofalldogs.com/*"
custom_domain = true

[[routes]]
pattern = "www.jackofalldogs.com/*"
custom_domain = true