name = "jackofalldogs"
main = "worker/index.js"
compatibility_date = "2025-08-07"

[build]
command = "npm run build"

[site]
bucket = "./dist"

[custom_domains]
"jackofalldogs.com" = { override_existing_dns_record = true }
"www.jackofalldogs.com" = { override_existing_dns_record = true }